// PROFILE
export const EDIT_PROFILE = 'EDIT_PROFILE'
export const DELETE_PROFILE = 'DELETE_PROFILE'
export const LOGOUT_USER = 'LOGOUT_USER'

// POSTS
export const CREATE_POST = 'CREATE_POST'
export const FETCH_POSTS = 'FETCH_POSTS'
export const DELETE_POST = 'DELETE_POST'
export const CREATE_POST_SUCCRESS = 'CREATE_POST_SUCCRESS'
export const CREATE_POST_ERROR = 'CREATE_POST_ERROR'

// COMMENTS
export const CREATE_COMMENT = 'CREATE_COMMENT'
export const DELETE_COMMENT = 'DELETE_COMMENT'

// ALERT
export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR'