// POSTS
export const CREATE_POST = 'CREATE_POST';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_ERROR = 'CREATE_POST_ERROR';
export const GET_POSTS = 'GET_POSTS';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const UPDATE_POST = 'UPDATE_POST';
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS';
export const UPDATE_POST_ERROR = 'UPDATE_POST_ERROR';
export const DELETE_POST = 'DELETE_POST';

export const RETRIEVE_POSTS = 'RETRIEVE_POSTS';
export const RETRIEVE_POST = 'RETRIEVE_POST';

// COMMENTS
export const CREATE_COMMENT = 'CREATE_COMMENT';
export const UPDATE_COMMENT = 'UPDATE_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';

export const RETRIEVE_COMMENTS = 'RETRIEVE_COMMENTS';
export const COUNT_COMMENTS = 'COUNT_COMMENTS';

// USERS
export const GET_USER = 'GET_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';
export const DELETE_USER = 'DELETE_USER';
export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const GET_ALL_USER = 'GET_ALL_USER';