import {
    CREATE_POST,
    UPDATE_POST,
    DELETE_POST,
    RETRIEVE_POST,
    RETRIEVE_POSTS,
    CREATE_COMMENT,
    UPDATE_COMMENT,
    DELETE_COMMENT,
    RETRIEVE_COMMENTS,
    COUNT_COMMENTS,
    GET_ALL_USER,
    UPDATE_USER,
    DELETE_USER,
    GET_CURRENT_USER,
    GET_ALL_USER
} from './actions';