// POST
export const CREATE_POST = 'CREATE_POST'
export const CREATE_POST_SUCCRESS = 'CREATE_POST_SUCCESS'
export const GET_POST_BEGIN = 'GET_POST_BEGIN'
export const FETCH_POSTS = 'FETCH_POSTS'
export const DELETE_POST = 'DELETE_POST'

// COMMENTS
export const CREATE_COMMENT = 'SETUP_USER_SUCCESS'
export const DELETE_COMMENT = 'DELETE_COMMENT'

// PROFILE
export const EDIT_PROFILE = 'EDIT_PROFILE'
export const DELETE_PROFILE = 'DELETE_PROFILE'
export const LOGOUT_USER = 'LOGOUT_USER'

// ALERT
export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR'